# SQLite version 3.x
#   gem install sqlite3-ruby (not necessary on OS X Leopard)

development: &default
  adapter: mysql
  user: root
  database: pairwise_development

test: &test
  <<: *default
  database: pairwise_test

cucumber:
  <<: *test

